version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=4
      - VECTOR_DB_PATH=/data/vector_db
    volumes:
      - .:/app
      - vector_db:/data/vector_db

volumes:
  vector_db: